version: '3.9'

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5555:5432"
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
  client:
    image: client-w3
    volumes:
      - ./react-client:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    environment:
      REACT_APP_SOCKET_ENDPOINT: http://localhost:3333
  backend:
    image: backend-w3
    volumes:
      - ./backend-service:/app
      - /app/node_modules
    ports:
      - "3333:3333"
    environment:
      PORT: 3333
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: database
      DB_PORT: 5432
      DB_HOST: postgres
      CORS_ORIGIN: http://localhost:8080
      CORS_METHODS: GET,POST
      ETH_NODE_API_KEY:
      ETH_NETWORK: goerli
volumes:
  postgres_data:
    driver: local
